name: CD - Kafka Accelerator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Helm ArgoCD Sync 
      run: echo Helm ArgoCD Synced Successfully !!
    
    - name: Pod Validation 
      run: echo Pod Validation Completed Successfully !!
