name: CI-CD Kafka Accelerator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Git Checkout 
      run: echo Git Checkout Successfully !!
    
    - name: Maven Build 
      run: echo Maven Build Completed Successfully !!

    - name: Test 
      run: echo Test Completed Successfully !!

    - name: Sonar 
      run: echo Code Scan Successfully !!
    
    - name: Docker 
      run: echo Docker Image Build Completed Successfully !!

    - name: Artifacts Publish 
      run: echo Artifact Published Successfully !!

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Helm ArgoCD Sync 
      run: echo Helm ArgoCD Synced Successfully !!
    
    - name: Pod Validation 
      run: echo Pod Validation Completed Successfully !!
